name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps (for selenium/plotly headless)
        run: sudo apt-get update && sudo apt-get install -y chromium-driver chromium || true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (flake8)
        run: flake8 src || true

      - name: Type check (mypy)
        run: mypy src || true

      - name: Run tests
        run: pytest -q --disable-warnings --maxfail=1
